{ config, pkgs, pkgsUnstable, lib, ... }:

{
  imports = [
      ../modules/apps/adguardhome.nix
      ../modules/apps/bash.nix
      ../modules/apps/cockpit/cockpit-podman.nix
      ../modules/apps/cockpit/cockpit-simple.nix
      ../modules/apps/exodus.nix
      ../modules/apps/firefox.nix
      ../modules/apps/fish.nix
      ../modules/apps/fluent-gtk-theme.nix
      ../modules/apps/freefilesync-unstable.nix
      ../modules/apps/home-assistant.nix
      ../modules/apps/homepage.nix
      ../modules/apps/jellyfin.nix
      ../modules/apps/librewolf.nix
      ../modules/apps/logitech.nix
      ../modules/apps/nano.nix
      ../modules/apps/nextcloud.nix
      ../modules/apps/openrgb.nix
      ../modules/apps/plexserver.nix
      ../modules/apps/podman.nix
      ../modules/apps/python/chainladder-flake.nix
      ../modules/apps/python/chainladder.nix
      ../modules/apps/scrutiny.nix
      ../modules/apps/steam.nix
      ../modules/apps/sweethome.nix
      ../modules/apps/thunderbird.nix
      ../modules/apps/undervolting.nix
      ../modules/apps/vaultwarden.nix
      ../modules/apps/video-downloader.nix
      ../modules/apps/vscode.nix
      ../modules/apps/wireguard/networkd-server.nix
      ../modules/apps/wireguard/proton-client.nix
      ../modules/apps/wireguard/quick-server.nix
      ../modules/bundles/datapro.nix
      ../modules/bundles/development.nix
      ../modules/bundles/gaming.nix
      ../modules/bundles/multimedia.nix
      ../modules/bundles/netpro.nix
      ../modules/bundles/office.nix
      ../modules/bundles/python.nix
      ../modules/bundles/securitypro.nix
      ../modules/bundles/videopro.nix
      ../modules/containers/nspawn/adguardhome.nix
      ../modules/containers/nspawn/cockpit.nix
      ../modules/containers/nspawn/home-assistant.nix
      ../modules/containers/nspawn/homepage.nix
      ../modules/containers/nspawn/jellyfin.nix
      ../modules/containers/nspawn/nextcloud.nix
      ../modules/containers/nspawn/plexserver.nix
      ../modules/containers/nspawn/rclone-cloud.nix
      ../modules/containers/nspawn/samba.nix
      ../modules/containers/nspawn/scrutiny.nix
      ../modules/containers/nspawn/sshfs.nix
      ../modules/containers/nspawn/vaultwarden.nix
      ../modules/containers/nspawn/wireguard-networkd.nix
      ../modules/containers/nspawn/wireguard-quick.nix
      ../modules/containers/nspawn/youtubedl.nix
      ../modules/desktop/codecs.nix
      ../modules/desktop/gnome/autologin.nix
      ../modules/desktop/gnome/gamestation.nix
      ../modules/desktop/gnome/mleborgne.nix
      ../modules/desktop/gnome/OLD_SYSTEM_SUSPEND.nix
      ../modules/desktop/pipewire.nix
      ../modules/flatpaks/kdenlive.nix
      ../modules/flatpaks/vscode.nix
      ../modules/forks/librewolf.nix
      ../modules/hardware/amdcpu.nix
      ../modules/hardware/amdgpu.nix
      ../modules/hardware/bluetooth.nix
      ../modules/hardware/intelcpu.nix
      ../modules/hardware/intelgpu.nix
      ../modules/hardware/nvidia.nix
      ../modules/hardware/printing.nix
      ../modules/hardware/rtl8125.nix
      ../modules/imports.nix
      ../modules/misc/corsair.nix
      ../modules/misc/docker.nix
      ../modules/misc/flatpak.nix
      ../modules/misc/iphone.nix
      ../modules/misc/libvirt.nix
      ../modules/misc/looking-glass.nix
      ../modules/misc/mdadm.nix
      ../modules/misc/mleupdater.nix
      ../modules/misc/networkd.nix
      ../modules/misc/networkmanager.nix
      ../modules/misc/nixos-containers.nix
      ../modules/misc/pci-passthrough.nix
      ../modules/misc/podman.nix
      ../modules/misc/samba.nix
      ../modules/misc/sshfs.nix
      ../modules/services/system-gocryptfs.nix
      ../modules/services/user-fstab-mount.nix
  ];
}
